### ISSUE TITLE
Website Peer Review 

### ISSUE THREAD

**Issue by llloreda1** [arosemond1/WebTech_project#1]
Hello Alexander, I just want to tell you that I liked your website and its content. It is looking really good, still, there are some suggestions: 

Technical Issues:
1) The suggestions table is embedded in all the pages on the website, and the tab link for the suggestions site is linked to the home page, it would be more helpful if you only had the suggestions table on its own section. The other possibility is to delete the suggestions page. 
2) The site map tab is the same as the site map that goes across the web page. Delete the site map tab. 

Content Suggestions:
1) You could add videos or pictures from the animes/mangas to show a recap of what they are about. 
2) Add more information about other animes or write some recommendations on the animes listed.

**Comment by arosemond1** [comment]
Thank you for your suggestions. I did remove the suggestions table from every page.
