### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by faijachoudhury01** [arosemond1/WebTech_project#2]
I really liked the way your webpage. It can easily grab the attention of the user.

Technical Issue:
* In the suggestion the option to choose the anime type, allows you to choose all three of the options. I was not sure that was intentional. 
* Since you have a tab for suggestions, maybe remove the suggestion box from under the other pages.

Content:
* it would be really cool if you could add trailers to the shoes that you mentioned.
* adding a comment section for people to share the experience. it can help people connect and share their ratings.

**Comment by arosemond1** [comment]
Thank you for your feedback. To your first point, to some extent, it was intentional most anime comes from the written form, so having that option, a person could recommend both or only one. I did remove the suggestions tab.
